- name: Azure App Configuration Sync
  uses: Azure/AppConfiguration-Sync@v1.1.3
  with:
    # Path to the configuration file in the repo, relative to the repo root. Also supports glob patterns and multiple files
    configurationFile: 
    # Format of the configuration file. Valid values are: json, yaml, properties
    format: 
    # Connection string for the App Configuration instance
    connectionString: 
    # Separator used when flattening the configuration file to key-value pairs
    separator: 
    # Specifies whether to use a strict sync which will make the App Configuration instance exactly match the configuration file (deleting key-values not in the configuration file). Defaults to false
    strict: # optional
    # Prefix that will be added to the front of the keys
    prefix: # optional
    # Label to use when setting the key-value pairs. If not specified, a null label will be used
    label: # optional
    # Max depth (positive number) for flattening the configuration file
    depth: # optional
    # Stringified form of a JSON object with the following shape: { [propertyName: string]: string; }
    tags: # optional
    # Content type associated with the values
    contentType: # optional
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BAY_014B0E610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BAY_014B0E610 }}
          action: "close"
          
